// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itgllbuotyivuzwmprkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0Z2xsYnVvdHlpdnV6d21wcmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzQyNTEsImV4cCI6MjA1OTg1MDI1MX0.vRENsavnTj5tWFk_F2PNl3WT1B4L8CvWpuI4nhdMYdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);